import './globals.css'

import Navbar from './navbar.js'
import Footer from './footer.js'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar></Navbar>
      <body>
        {children}
      </body>
      <Footer></Footer>
    </html>
  )
}
